sisso_path: '/home/gyrudgyrud21/tRP/SISSO/run/2_2' # sisso path
save_path: '/home/gyrudgyrud21/tRP/SISSO/result/2_2' # save path

data:
  train: '/home/gyrudgyrud21/tRP/Data/train_source.csv'
  test: '/home/gyrudgyrud21/tRP/Data/test_source.csv'

extraction: 
  max_complexity: 9 # the maximum complexity of the descriptors
  min_complexity: 1 # the minimum complexity of the descriptors
  feature_list: ['rA', 'rB', 'rX', 'nA', 'nB', 'nX', 'xX'] # feature list that used in the SISSO input

columns:
  label: Label # label name in the dataset
