save_path: '/scratch/x3100a06/tRP/SISSO/result/2_1' # save path

criterion: 
  n_value: 1 # An+1BnX3n+1 (n=1,2,3,...)
  halogen: False # if chalcogen: False, halogen: True
  chalcogen: True # if chalcogen: True, halogen: False
  feature_list: ['rA', 'rB', 'rX', 
                 'nA', 'nB', 'nX', 
                 'xA', 'xB', 'xX',
                 'iA', 'iB', 'iX',
                 'vA', 'vB', 'vX'] # fetures list
  descriptor: '((rA/rX)+(log(rB)/exp(nA)))' # a descriptor
  descriptor_path: '/scratch/x3100a06/tRP/SISSO/result/2_1/descriptors.csv' # the path of the descriptor file
  data_path: '/scratch/x3100a06/tRP/Data/Table.S1_source.csv' # the path of the data file
  except_source: 'Hybrid' # choose Handbook or ICSD+ or Hybrid

columns:
  label: Label # label name in the dataset
