save_path: '/home/gyrudgyrud21/tRP/SISSO/result/2_2' # save path

criterion: 
  n_value: 1 # An+1BnX3n+1 (n=1,2,3,...)
  halogen: True # if chalcogen: False, halogen: True
  chalcogen: False # if chalcogen: True, halogen: False
  feature_list: ['rA', 'rB', 'rX', 
                 'nA', 'nB', 'nX', 
                 'xX'] # fetures list
  descriptor: '((log(rB)/(nA)^2)-(rX/rA))' # a descriptor
  descriptor_path: '/home/gyrudgyrud21/tRP/SISSO/result/2_2/descriptors.csv' # the path of the descriptor file
  data_path: '/home/gyrudgyrud21/tRP/Data/Table.S1_source.csv' # the path of the data file
  except_source: 'Hybrid' # choose Handbook or ICSD+ or Hybrid

columns:
  label: Label # label name in the dataset
