compound: Sr2RuO4 # Full name of the compound to be predicted
level: 1          # n-value in RP phase
bias: False       # If False, bias will be automatically determined based on tRP criteria

A1: Sr            # Element information of A1 site
A2: Sr            # Element information of A2 site
B1: Ru            # Element information of B1 site
B2: Ru            # Element information of B2 site
X1: O             # Element information of X1 site
X2: O             # Element information of X2 site

A1_ratio: 1       # Ratio at the A1 site
A2_ratio: 1       # Ratio at the A2 site
B1_ratio: 0.5     # Ratio at the B1 site
B2_ratio: 0.5     # Ratio at the B2 site
X1_ratio: 2       # Ratio at the X1 site
X2_ratio: 2       # Ratio at the X2 site

A1_CN: 9          # C.N at the A1 site
A2_CN: 9          # C.N at the A2 site
B1_CN: 6          # C.N at the B1 site
B2_CN: 6          # C.N at the B2 site
X1_CN: 6          # C.N at the X1 site
X2_CN: 6          # C.N at the X2 site

A1_Q: 2           # Oxidation State at the A1 site
A2_Q: 2           # Oxidation State at the A2 site
B1_Q: 4           # Oxidation State at the B1 site
B2_Q: 4           # Oxidation State at the B2 site
X1_Q: -2          # Oxidation State at the X1 site
X2_Q: -2          # Oxidation State at the X2 site

shannon_radius: /scratch/x3100a06/tRP/Data/Shannon_Radii_Dict.json


