save_path: '/scratch/x3100a06/tRP/SISSO/result' # save path

criterion: 
  n_value: 1 # An+1BnX3n+1 (n=1,2,3,...)
  halogen: True # if chalcogen: False, halogen: True
  chalcogen: False # if chalcogen: True, halogen: False
  feature_list: ['rA', 'rB', 'rX', 'xX'] # fetures list
  descriptor: '(((rB/rA))^2+sqrt((rX/rB)))' # a descriptor
  descriptor_path: '/scratch/x3100a06/tRP/SISSO/result/descriptors.csv' # the path of the descriptor file
  data_path: '/scratch/x3100a06/tRP/Data/Table.S1_source.csv' # the path of the data file
  except_source: 'Hybrid' # choose Handbook or ICSD+ or Hybrid

columns:
  label: Label # label name in the dataset
